"""20210916
create table: stock_basic_info

Revision ID: 06b7f511706c
Revises: 
Create Date: 2021-09-16 15:14:17.856332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06b7f511706c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_basic_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_code', sa.String(length=10), nullable=False, comment='股票代號'),
    sa.Column('stock_name', sa.String(length=40), nullable=False, comment='股票名稱'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_code'),
    sa.UniqueConstraint('stock_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_basic_info')
    # ### end Alembic commands ###
