"""20210916
create table: daily_price_info

Revision ID: 75336d0a7a65
Revises: 06b7f511706c
Create Date: 2021-09-16 15:21:13.572682

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '75336d0a7a65'
down_revision = '06b7f511706c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_price_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_basic_info_id', sa.Integer(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True, comment='成交量(張)'),
    sa.Column('closing_price', sa.Float(), nullable=False, comment='收盤價格'),
    sa.Column('opening_price', sa.Float(), nullable=False, comment='開盤價格'),
    sa.Column('highest_price', sa.Float(), nullable=False, comment='最高價格'),
    sa.Column('lowest_price', sa.Float(), nullable=False, comment='最低價格'),
    sa.Column('date', sa.Date(), nullable=False, comment='交易日期'),
    sa.ForeignKeyConstraint(['stock_basic_info_id'], ['stock_basic_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('stock_basic_info', 'stock_code',
               existing_type=mysql.VARCHAR(length=10),
               comment=None,
               existing_comment='股票代號',
               existing_nullable=False)
    op.alter_column('stock_basic_info', 'stock_name',
               existing_type=mysql.VARCHAR(length=40),
               comment=None,
               existing_comment='股票名稱',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_basic_info', 'stock_name',
               existing_type=mysql.VARCHAR(length=40),
               comment='股票名稱',
               existing_nullable=False)
    op.alter_column('stock_basic_info', 'stock_code',
               existing_type=mysql.VARCHAR(length=10),
               comment='股票代號',
               existing_nullable=False)
    op.drop_table('daily_price_info')
    # ### end Alembic commands ###
